# Generated by Django 5.0 on 2023-12-12 10:32

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_post_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='doc classification')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Createtime')),
                ('edit_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Modifytime')),
            ],
            options={
                'verbose_name': 'doc classification',
                'verbose_name_plural': 'doc classification',
            },
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='blank-profile-picture.png', null=True, upload_to='post_images'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Message')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='time')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Message',
            },
        ),
    ]
